### ISSUE TITLE
Got an error when pushed saves from android device

### ISSUE THREAD

**Issue by danielavdalian** [blake502/balatro-mobile-maker#54] opened 2024-04-25 23:12 UTC
When I pull the save from my android device, I get this error: 
![image](https://github.com/blake502/balatro-mobile-maker/assets/78348541/c140131c-87b4-4625-a96f-623172e42ed7)
I got the same error when using a save from steam to my android

**Comment by danielavdalian** [comment] 2024-04-26 08:37
Update:

The error only happens when the version of Balatro of both devices is different.
Like:

Android Version: 1.0.0.i-FULL
Windows Version: 1.0.0.n-FULL
 Android ------> Windows **FAIL**
 Windows------> Android **FAIL**

**Comment by blake502** [comment] 2024-04-26 12:19
Good to know. I also encountered this issue, but have a fix planned.

To fix this manually, copy your saves from Android -> to Windows. Then, on the Windows side, delete any 0kb file in the `%AppData%\Balatro` directory (make sure to check sub-directories).

On Android, clear your saves entirely using the app manager, then copy the saves back to Android.

The cause of the issue I encountered was because I "touch" every possible file on the Android side that might be included in the save before transferring to Windows... As a result, a couple of 0kb files are likely to be generated. Balatro will try to read those files as if they contain information-- which they do not.

**Comment by danielavdalian** [comment] 2024-04-26 14:17
Ok ok ok, got it, I will do that in the meantime. Thank you!

**Comment by danielavdalian** [comment] 2024-04-26 16:07
I fixed it with this PR: https://github.com/blake502/balatro-mobile-maker/pull/55

**Comment by danielavdalian** [comment] 2024-05-01 06:10
The beta 0.8.2 should fix your problem

**Closed** 2024-05-07 01:00 UTC
Labels: bug
